baseURL = "https://tingy.dev/"
languageCode = "en-us"
title = "The DevOps Journey"
theme = "etch"
description = "Streamline Your Workflow with AWS and Kubernetes"

[params]
  description = "Streamline Your Workflow with AWS and Kubernetes"
  copyright = "Copyright © 2023 Ting Yang"
  dark = "off"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true